/*
  Military Gentleman Trainer — exercise library (Strength A + B, Phase 0).
  Source of truth: military_gentleman_knowledge_base.html §6 Foundation Exercise Library.
  STRICT RULE: only knowledge-base exercises. Warm-up + Mobility data arrive in TASK-019.

  Classic script (no ES module) so trainer.html works over file://.
  scripts/generate-cards.mjs reads this same file at author-time.

  Per-exercise card-generation metadata per docs/prd.md § Data Model +
  docs/exercise-card-prompt.md. `sequence` is the "Main sequence" text the
  master prompt needs per card (mirrors the Dead Bug example).
  `view` enum: side | front | side-ground-plane. Floor work always gets a
  ground plane via the master prompt regardless of view (side-plank is `front`
  because its shape is unreadable from the side).

  approved:false until Ivan reviews the generated card against a known-good
  source (approval gate, FR-012). videoUrl stays null until Ivan picks ONE
  demonstration per exercise (KB resource rule: no random browsing).
*/
var MGT_EXERCISES = [
  // ── Strength A — push, pull, squat, core ──────────────────────────────
  {
    id: "band-chest-press",
    name: "Band Chest Press",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/band-chest-press.webp",
    printImage: "images/band-chest-press.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "chest, shoulders, triceps",
    sequence: "Start position: standing, band anchored behind at chest height, hands at chest, elbows bent. End position: both arms pressed straight forward at chest height, band taut. Return slowly to the start.",
    commonMistake: "shrugging the shoulders while pressing",
    correct: "shoulders stay down and relaxed; push forward, return slowly",
    cues: ["Anchor the band behind you", "Return slowly", "Do not shrug"],
    tempo: "Press out controlled, return slowly",
    primaryFault: "shoulder shrug",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-06 — text-free batch, movement verified"
  },
  {
    id: "band-row",
    name: "Band Row",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/band-row.webp",
    printImage: "images/band-row.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "upper back, posture muscles",
    sequence: "Start position: facing the anchor, arms extended forward holding the band. End position: elbows pulled back past the ribs, shoulder blades drawn down into the “back pockets”, torso upright and still.",
    commonMistake: "leaning backward to finish the pull",
    correct: "torso stays upright; shoulder blades pull down and back",
    cues: ["Pull elbows back", "Blades into back pockets", "Do not lean back"],
    tempo: "Slow and controlled both ways",
    promptNotes: "The elastic resistance band must be clearly visible, taut and attached to the hands in BOTH frames — in the finish frame it stays stretched from the anchor point to the hand at the ribs. In the common-mistake inset show the WRONG version (torso leaning backward, marked with a red X) next to the correct upright version.",
    primaryFault: "leaning backward",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-06 — text-free batch, movement verified"
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight Squat",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/bodyweight-squat.webp",
    printImage: "images/bodyweight-squat.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "legs, hips",
    sequence: "Start position: standing tall, feet about shoulder-width. End position: hips sat back and down, knees following the toes, trunk steady. Stand fully tall to finish each rep.",
    commonMistake: "knees collapsing inward while chasing depth",
    correct: "sit back, knees track over the toes, only as deep as control allows",
    cues: ["Sit back", "Knees follow toes", "Stand fully tall"],
    tempo: "Slow, controlled reps",
    primaryFault: "knee collapse",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-06 — text-free batch, movement verified"
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/dead-bug.webp",
    printImage: "images/dead-bug.png",
    videoUrl: null,
    view: "side-ground-plane",
    frames: 1,
    muscles: "core, hip flexors",
    sequence: "ONE single large figure lying flat on its back on the mat, captured mid-movement, with this exact contralateral pairing: the LEFT arm reaches back overhead toward the floor behind the head (moving, blue) while the RIGHT leg extends long and low over the floor (moving, blue); meanwhile the RIGHT arm points straight up at the ceiling (held, grey) and the LEFT knee stays bent at 90 degrees with the shin parallel to the floor, foot off the floor (held, grey). Curved motion arrows trace the reaching arm's path overhead and the extending leg's path forward. Head and upper back stay flat on the mat.",
    commonMistake: "arching the low back",
    correct: "ribs down, low back stable, controlled reach",
    cues: ["Keep low back gently pressed down", "Move slowly", "Brace your core"],
    tempo: "Move slowly",
    promptNotes: "STRICT LAYOUT: exactly ONE large main figure filling the width of the image, plus exactly ONE small mistake/correct inset in a corner — no other panels, no repeated figures, no sequence strips. The main figure: complete body head to feet, side view, lying on its back on the mat, feet never resting on the floor. One arm up / opposite arm reaching overhead; one knee bent at 90 degrees / opposite leg extended low. Blue = the reaching arm and extending leg; grey = the held arm and bent leg. The inset: red X over a version whose lower back arches up off the mat; green check over the flat-back version.",
    primaryFault: "low-back arch",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-06 — text-free batch, movement verified"
  },
  {
    id: "front-plank",
    name: "Front Plank",
    category: "strength",
    dose: "Hold — stop before form fails",
    image: "images/front-plank.webp",
    printImage: "images/front-plank.png",
    videoUrl: null,
    view: "side-ground-plane",
    frames: 2,
    muscles: "trunk, core",
    sequence: "Single static hold: forearms on the floor under the shoulders, body one straight line from head to heels. Second frame shows the hold maintained with steady breathing; stop the set before the hips sag.",
    commonMistake: "hips sagging as the hold goes on",
    correct: "one straight line head to heels; end the set before form breaks",
    cues: ["Straight line head to heels", "Stop before hips sag", "Breathe steadily"],
    tempo: "Steady hold",
    primaryFault: "hip sag",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-06 — text-free batch, movement verified"
  },
  // ── Strength B — shoulders, back, legs, core ──────────────────────────
  {
    id: "band-overhead-press",
    name: "Band Overhead Press",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/band-overhead-press.webp",
    printImage: "images/band-overhead-press.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "shoulders, core stabilizers",
    sequence: "Start position: standing on the band, hands at shoulder height. End position: arms pressed straight overhead, ribs down, glutes lightly engaged, no lower-back arch.",
    commonMistake: "arching the lower back to press overhead",
    correct: "ribs down, glutes lightly engaged, press without arching",
    cues: ["Ribs down", "Glutes lightly engaged", "No lower-back arch"],
    tempo: "Press up controlled, lower slowly",
    primaryFault: "lower-back arch",
    videoCandidate: true,
    approved: false
  },
  {
    id: "band-face-pull",
    name: "Band Face Pull",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/band-face-pull.webp",
    printImage: "images/band-face-pull.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "rear shoulders, rotator cuff",
    sequence: "Start position: facing the door anchor set at head height, arms extended forward holding the band. End position: band pulled toward the face, elbows high and wide, shoulders staying down.",
    commonMistake: "shrugging the shoulders during the pull",
    correct: "elbows high, pull toward the face, shoulders stay down",
    cues: ["Pull toward your face", "Elbows high", "Do not shrug"],
    tempo: "Slow and controlled both ways",
    primaryFault: "shoulder shrug",
    videoCandidate: true,
    approved: false
  },
  {
    id: "band-lat-pulldown",
    name: "Band Lat Pulldown",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/band-lat-pulldown.webp",
    printImage: "images/band-lat-pulldown.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "lats, upper back",
    sequence: "Start position: under a high anchor, arms extended upward holding the band, chest tall. End position: elbows pulled down toward the ribs and “back pockets”, band in front of the body — never behind the neck.",
    commonMistake: "pulling the band behind the neck",
    correct: "band pulls down in front; elbows move toward ribs and back pockets",
    cues: ["Elbows toward back pockets", "Chest tall", "Never behind the neck"],
    tempo: "Pull down controlled, resist on the way up",
    primaryFault: "behind-the-neck pull",
    videoCandidate: true,
    approved: false
  },
  {
    id: "reverse-lunge",
    name: "Reverse Lunge",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/reverse-lunge.webp",
    printImage: "images/reverse-lunge.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "legs, hips, balance",
    sequence: "Start position: standing tall. End position: one leg stepped backward, both knees bent to about 90 degrees in a controlled descent, front knee tracking over the toes. Push back up to standing.",
    commonMistake: "front knee collapsing inward",
    correct: "controlled descent; front knee tracks over the toes",
    cues: ["Step backward", "Lower with control", "Knee follows toes"],
    tempo: "Controlled descent, steady rise",
    primaryFault: "knee collapse",
    videoCandidate: true,
    approved: false
  },
  {
    id: "band-romanian-deadlift",
    name: "Band Romanian Deadlift",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/band-romanian-deadlift.webp",
    printImage: "images/band-romanian-deadlift.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "hamstrings, glutes, posterior chain",
    sequence: "Start position: standing on the band, hands holding it at the thighs. End position: hips pushed back, torso hinged forward with a neutral spine, band taut. Stand back up by squeezing the glutes.",
    commonMistake: "rounding the back during the hinge",
    correct: "hips travel back, spine stays neutral; stand by squeezing the glutes",
    cues: ["Hips back", "Neutral spine", "Squeeze glutes to stand"],
    tempo: "Hinge slowly, stand with control",
    primaryFault: "rounded back",
    videoCandidate: true,
    approved: false
  },
  {
    id: "side-plank",
    name: "Side Plank",
    category: "strength",
    dose: "Hold each side — stop before form fails",
    image: "images/side-plank.webp",
    printImage: "images/side-plank.png",
    videoUrl: null,
    view: "front",
    frames: 2,
    muscles: "obliques, lateral hip stabilizers",
    sequence: "Single static hold on the floor: propped on one forearm, shoulder stacked over the elbow, feet stacked, hips lifted high so the body forms one straight line. Second frame shows the hold on the other side.",
    commonMistake: "hips dropping toward the floor",
    correct: "hips high, body straight, shoulder stacked over the elbow",
    cues: ["Hips high", "Body straight", "Shoulder stacked"],
    tempo: "Steady hold",
    primaryFault: "hip drop",
    videoCandidate: true,
    approved: false
  }
];
