/*
  Military Gentleman Trainer — exercise library (Strength A + B, Phase 0).
  Source of truth: military_gentleman_knowledge_base.html §6 Foundation Exercise Library.
  STRICT RULE: only knowledge-base exercises. Warm-up + Mobility data arrive in TASK-019.

  Classic script (no ES module) so trainer.html works over file://.
  scripts/generate-cards.mjs reads this same file at author-time.

  Per-exercise card-generation metadata per docs/prd.md § Data Model +
  docs/exercise-card-prompt.md. `sequence` is the "Main sequence" text the
  master prompt needs per card (mirrors the Dead Bug example).
  `view` enum: side | front | side-ground-plane. Floor work always gets a
  ground plane via the master prompt regardless of view (side-plank is `front`
  because its shape is unreadable from the side).

  approved:false until Ivan reviews the generated card against a known-good
  source (approval gate, FR-012). videoUrl stays null until Ivan picks ONE
  demonstration per exercise (KB resource rule: no random browsing).
*/
var MGT_EXERCISES = [
  // ── Strength A — push, pull, squat, core ──────────────────────────────
  {
    id: "band-chest-press",
    name: "Band Chest Press",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/band-chest-press.webp",
    printImage: "images/band-chest-press.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "chest, shoulders, triceps",
    sequence: "Start position: standing, band anchored behind at chest height, hands at chest, elbows bent. End position: both arms pressed straight forward at chest height, band taut. Return slowly to the start.",
    commonMistake: "shrugging the shoulders while pressing",
    correct: "shoulders stay down and relaxed; push forward, return slowly",
    cues: ["Anchor the band behind you", "Return slowly", "Do not shrug"],
    tempo: "Press out controlled, return slowly",
    primaryFault: "shoulder shrug",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "band-row",
    name: "Band Row",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/band-row.webp",
    printImage: "images/band-row.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "upper back, posture muscles",
    sequence: "Start position: facing the anchor, arms extended forward holding the band. End position: elbows pulled back past the ribs, shoulder blades drawn down into the “back pockets”, torso upright and still.",
    commonMistake: "leaning backward to finish the pull",
    correct: "torso stays upright; shoulder blades pull down and back",
    cues: ["Pull elbows back", "Blades into back pockets", "Do not lean back"],
    tempo: "Slow and controlled both ways",
    promptNotes: "The elastic resistance band must be clearly visible, taut and attached to the hands in BOTH frames — in the finish frame it stays stretched from the anchor point to the hand at the ribs. In the common-mistake inset show the WRONG version (torso leaning backward, marked with a red X) next to the correct upright version.",
    primaryFault: "leaning backward",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight Squat",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/bodyweight-squat.webp",
    printImage: "images/bodyweight-squat.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "legs, hips",
    sequence: "Start position: standing tall, feet about shoulder-width. End position: hips sat back and down, knees following the toes, trunk steady. Stand fully tall to finish each rep.",
    commonMistake: "knees collapsing inward while chasing depth",
    correct: "sit back, knees track over the toes, only as deep as control allows",
    cues: ["Sit back", "Knees follow toes", "Stand fully tall"],
    tempo: "Slow, controlled reps",
    primaryFault: "knee collapse",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/dead-bug.webp",
    printImage: "images/dead-bug.png",
    videoUrl: null,
    view: "side-ground-plane",
    frames: 1,
    muscles: "core, hip flexors",
    sequence: "ONE single large figure lying flat on its back on the mat, captured mid-movement, with this exact contralateral pairing: the LEFT arm reaches back overhead toward the floor behind the head (moving, blue) while the RIGHT leg extends long and low over the floor (moving, blue); meanwhile the RIGHT arm points straight up at the ceiling (held, grey) and the LEFT knee stays bent at 90 degrees with the shin parallel to the floor, foot off the floor (held, grey). Curved motion arrows trace the reaching arm's path overhead and the extending leg's path forward. Head and upper back stay flat on the mat.",
    commonMistake: "arching the low back",
    correct: "ribs down, low back stable, controlled reach",
    cues: ["Keep low back gently pressed down", "Move slowly", "Brace your core"],
    tempo: "Move slowly",
    promptNotes: "STRICT LAYOUT: exactly ONE large main figure filling the width of the image, plus exactly ONE small mistake/correct inset in a corner — no other panels, no repeated figures, no sequence strips. The main figure: complete body head to feet, side view, lying on its back on the mat, feet never resting on the floor. One arm up / opposite arm reaching overhead; one knee bent at 90 degrees / opposite leg extended low. Blue = the reaching arm and extending leg; grey = the held arm and bent leg. The inset: red X over a version whose lower back arches up off the mat; green check over the flat-back version.",
    primaryFault: "low-back arch",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "front-plank",
    name: "Front Plank",
    category: "strength",
    dose: "Hold — stop before form fails",
    image: "images/front-plank.webp",
    printImage: "images/front-plank.png",
    videoUrl: null,
    view: "side-ground-plane",
    frames: 2,
    muscles: "trunk, core",
    sequence: "Single static hold: forearms on the floor under the shoulders, body one straight line from head to heels. Second frame shows the hold maintained with steady breathing; stop the set before the hips sag.",
    commonMistake: "hips sagging as the hold goes on",
    correct: "one straight line head to heels; end the set before form breaks",
    cues: ["Straight line head to heels", "Stop before hips sag", "Breathe steadily"],
    tempo: "Steady hold",
    primaryFault: "hip sag",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  // ── Strength B — shoulders, back, legs, core ──────────────────────────
  {
    id: "band-overhead-press",
    name: "Band Overhead Press",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/band-overhead-press.webp",
    printImage: "images/band-overhead-press.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "shoulders, core stabilizers",
    sequence: "Start position: standing on the band, hands at shoulder height. End position: arms pressed straight overhead, ribs down, glutes lightly engaged, no lower-back arch.",
    commonMistake: "arching the lower back to press overhead",
    correct: "ribs down, glutes lightly engaged, press without arching",
    cues: ["Ribs down", "Glutes lightly engaged", "No lower-back arch"],
    tempo: "Press up controlled, lower slowly",
    movingLimbs: "both arms (blue from shoulder to hand)",
    heldLimbs: "both legs, standing (grey)",
    primaryFault: "lower-back arch",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "band-face-pull",
    name: "Band Face Pull",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/band-face-pull.webp",
    printImage: "images/band-face-pull.png",
    videoUrl: null,
    view: "front",
    frames: 2,
    muscles: "rear shoulders, rotator cuff",
    sequence: "FRONT view, facing the viewer, STANDING FULLY UPRIGHT with straight legs and feet hip-width apart in BOTH frames — no squatting, no bent knees. Start position: both arms extended straight forward at head height holding the two ends of the band. End position: the band pulled toward the face — hands beside the ears, ELBOWS LIFTED HIGH AND FLARED WIDE OUT TO THE SIDES at shoulder height, forming a W shape with the arms; shoulders stay down away from the ears.",
    commonMistake: "shrugging the shoulders during the pull",
    correct: "elbows high, pull toward the face, shoulders stay down",
    cues: ["Pull toward your face", "Elbows high", "Do not shrug"],
    tempo: "Slow and controlled both ways",
    promptNotes: "SCENE GEOMETRY — critical: three-quarter front view. The band is attached to a door anchor at HEAD HEIGHT in front of the figure, visible at the upper edge of each frame; the band runs DOWNWARD-FORWARD from the anchor to the hands, taut. The figure NEVER stands on the band. The figure STANDS FULLY UPRIGHT in both frames: legs straight, feet hip-width, no squat, no bent knees, no wide stance. Only the arms move between frames.",
    movingLimbs: "both arms (blue from shoulder to hand)",
    heldLimbs: "both legs, standing (grey)",
    primaryFault: "shoulder shrug",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "band-lat-pulldown",
    name: "Band Lat Pulldown",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/band-lat-pulldown.webp",
    printImage: "images/band-lat-pulldown.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "lats, upper back",
    sequence: "Start position: under a high anchor, arms extended upward holding the band, chest tall. End position: elbows pulled down toward the ribs and “back pockets”, band in front of the body — never behind the neck.",
    commonMistake: "pulling the band behind the neck",
    correct: "band pulls down in front; elbows move toward ribs and back pockets",
    cues: ["Elbows toward back pockets", "Chest tall", "Never behind the neck"],
    tempo: "Pull down controlled, resist on the way up",
    movingLimbs: "both arms (blue from shoulder to hand)",
    heldLimbs: "both legs and torso (grey legs)",
    primaryFault: "behind-the-neck pull",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "reverse-lunge",
    name: "Reverse Lunge",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/reverse-lunge.webp",
    printImage: "images/reverse-lunge.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "legs, hips, balance",
    sequence: "Start position: standing tall. End position: one leg stepped backward, both knees bent to about 90 degrees in a controlled descent, front knee tracking over the toes. Push back up to standing.",
    commonMistake: "front knee collapsing inward",
    correct: "controlled descent; front knee tracks over the toes",
    cues: ["Step backward", "Lower with control", "Knee follows toes"],
    tempo: "Controlled descent, steady rise",
    promptNotes: "Both feet stay on the SAME flat floor level — absolutely no step, platform, box or ledge anywhere in the scene. In the lunge frame the rear knee hovers just above the floor and both knees bend to about 90 degrees.",
    movingLimbs: "the stepping (rear) leg (blue)",
    heldLimbs: "the front support leg (grey); arms relaxed at the sides (grey)",
    primaryFault: "knee collapse",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "band-romanian-deadlift",
    name: "Band Romanian Deadlift",
    category: "strength",
    dose: "Sets × reps per weekly target",
    image: "images/band-romanian-deadlift.webp",
    printImage: "images/band-romanian-deadlift.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "hamstrings, glutes, posterior chain",
    sequence: "Start position: standing on the band, hands holding it at the thighs. End position: hips pushed back, torso hinged forward with a neutral spine, band taut. Stand back up by squeezing the glutes.",
    commonMistake: "rounding the back during the hinge",
    correct: "hips travel back, spine stays neutral; stand by squeezing the glutes",
    cues: ["Hips back", "Neutral spine", "Squeeze glutes to stand"],
    tempo: "Hinge slowly, stand with control",
    movingLimbs: "the hinging torso/hips (shown by the arrow — torso stays navy)",
    heldLimbs: "both arms hanging and holding the band (grey), both legs (grey)",
    primaryFault: "rounded back",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "side-plank",
    name: "Side Plank",
    category: "strength",
    dose: "Hold each side — stop before form fails",
    image: "images/side-plank.webp",
    printImage: "images/side-plank.png",
    videoUrl: null,
    view: "front",
    frames: 1,
    muscles: "obliques, lateral hip stabilizers",
    sequence: "ONE single large figure holding a side plank on the mat: the body is propped on the bent FOREARM which lies flat along the mat, elbow bent 90 degrees directly under the shoulder, upper arm vertical. Feet stacked, hips lifted high so head–hips–heels form one straight diagonal line. The free arm rests along the top hip. A dashed reference line runs along the straight body line.",
    commonMistake: "hips dropping toward the floor",
    correct: "hips high, body straight, shoulder stacked over the elbow",
    cues: ["Hips high", "Body straight", "Shoulder stacked"],
    tempo: "Steady hold",
    promptNotes: "STRICT LAYOUT: exactly ONE large main figure filling the width of the image, plus exactly ONE small mistake/correct inset in a corner — no other panels, no repeated figures. A straight-arm / palm-supported side plank must NOT appear anywhere, not even in the inset: every figure on this card rests on the bent forearm, flat on the mat, elbow under shoulder. Inset: red X over a forearm side plank whose hips sag toward the floor; green check over the straight-line forearm version.",
    movingLimbs: "nothing — this is a static hold; use NO blue limbs",
    heldLimbs: "the support forearm and both legs (grey)",
    primaryFault: "hip drop",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  // ── Warm-up — KB §4 Chapter 3 (5–7 min before every strength session) ──
  {
    id: "neck-mobility",
    name: "Neck Mobility",
    category: "warmup",
    dose: "30–40 sec",
    image: "images/neck-mobility.webp",
    printImage: "images/neck-mobility.png",
    videoUrl: null,
    view: "front",
    frames: 2,
    muscles: "neck",
    sequence: "Frame 1: standing tall, head turned gently to one side (motion arrows showing turn left–center–right). Frame 2: head tilted, ear moving toward the shoulder, with small arrows for the up/down nod. All movements slow and smooth.",
    commonMistake: "fast circles or forcing the end range",
    correct: "slow, smooth turns and tilts — easy range only",
    cues: ["Turn left, centre, right", "Then up and down", "Then ear toward shoulder"],
    tempo: "Slow and smooth",
    primaryFault: "forcing end range",
    videoCandidate: false,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "shoulder-circles",
    name: "Shoulder Circles",
    category: "warmup",
    dose: "10 forward + 10 backward",
    image: "images/shoulder-circles.webp",
    printImage: "images/shoulder-circles.png",
    videoUrl: null,
    view: "front",
    frames: 1,
    muscles: "shoulders",
    sequence: "One standing figure, arms relaxed at the sides, with large circular motion arrows around both shoulders showing big, slow circles (one arrow forward, one backward). Neck long and relaxed.",
    commonMistake: "shrugging and rushing",
    correct: "large, slow circles with a relaxed neck",
    cues: ["Large, slow circles", "Keep neck relaxed"],
    tempo: "Slow",
    primaryFault: "shrugging",
    videoCandidate: false,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "arm-swings",
    name: "Arm Swings",
    category: "warmup",
    dose: "20 reps",
    image: "images/arm-swings.webp",
    printImage: "images/arm-swings.png",
    videoUrl: null,
    view: "front",
    frames: 2,
    muscles: "chest, shoulders",
    sequence: "Frame 1: standing, arms crossed in front of the chest. Frame 2: arms swung open wide, chest open, with horizontal motion arrows showing the swing between the two positions. Smooth, continuous movement.",
    commonMistake: "jerky movement",
    correct: "smooth, controlled swings",
    cues: ["Cross arms in front", "Then open the chest"],
    tempo: "Smooth and continuous",
    primaryFault: "jerky movement",
    videoCandidate: false,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "thoracic-rotation",
    name: "Thoracic Rotation",
    category: "warmup",
    dose: "10 each side",
    image: "images/thoracic-rotation.webp",
    printImage: "images/thoracic-rotation.png",
    videoUrl: null,
    view: "front",
    frames: 2,
    muscles: "upper back",
    sequence: "Frame 1: standing, hands at chest, upper body rotated to one side while the hips stay square to the front (dashed line down the hips shows they don't move). Frame 2: rotation to the other side. Curved arrows at the shoulders show the turning motion.",
    commonMistake: "twisting the knees and hips along",
    correct: "hips face forward; only the upper body rotates",
    cues: ["Rotate the upper body", "Hips face forward"],
    tempo: "Controlled",
    primaryFault: "hip twist",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "hip-circles",
    name: "Hip Circles",
    category: "warmup",
    dose: "10 each direction",
    image: "images/hip-circles.webp",
    printImage: "images/hip-circles.png",
    videoUrl: null,
    view: "front",
    frames: 1,
    muscles: "hips",
    sequence: "One standing figure with hands on hips and a large circular motion arrow around the pelvis showing smooth hip circles. Upright, tall posture throughout.",
    commonMistake: "collapsing the posture",
    correct: "tall posture, smooth circles",
    cues: ["Hands on hips", "Smooth circles"],
    tempo: "Smooth",
    primaryFault: "posture collapse",
    videoCandidate: false,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "cat-cow",
    name: "Cat–Cow",
    category: "warmup",
    dose: "10 reps",
    image: "images/cat-cow.webp",
    printImage: "images/cat-cow.png",
    videoUrl: null,
    view: "side-ground-plane",
    frames: 2,
    muscles: "spine, core",
    sequence: "Frame 1 (Cat): on hands and knees on the mat, spine rounded gently upward, head relaxed down. Frame 2 (Cow): same position, spine dipped gently downward, head lifted slightly. Curved arrows along the spine show the flow between the two shapes.",
    commonMistake: "forcing the low back",
    correct: "gentle spinal flexion and extension, moving with the breath",
    cues: ["Move with your breath", "Gentle range only"],
    tempo: "Slow, with the breath",
    primaryFault: "forcing the low back",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "march-in-place",
    name: "March in Place",
    category: "warmup",
    dose: "60 sec",
    image: "images/march-in-place.webp",
    printImage: "images/march-in-place.png",
    videoUrl: null,
    view: "side",
    frames: 1,
    muscles: "legs, hips",
    sequence: "One standing figure marching in place: one knee lifted to a natural height (moving, blue), the opposite arm swinging forward, the support leg grounded (grey). Small arrows show the natural knee lift and arm swing rhythm.",
    commonMistake: "turning it into cardio fatigue",
    correct: "natural knee lift, easy arm swing, controlled breathing",
    cues: ["Natural knee lift", "Easy arm swing", "Controlled breathing"],
    tempo: "Relaxed rhythm",
    primaryFault: "overexertion",
    videoCandidate: false,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  // ── Mobility — KB §5 Chapter 4 (12–18 min, non-strength days or after) ──
  {
    id: "doorway-chest-opener",
    name: "Doorway Chest Opener",
    category: "mobility",
    dose: "20–30 sec/side",
    image: "images/doorway-chest-opener.webp",
    printImage: "images/doorway-chest-opener.png",
    videoUrl: null,
    view: "side",
    frames: 1,
    muscles: "chest",
    sequence: "One standing figure in a doorway: forearm resting on the door frame at shoulder height, body leaning gently forward through the opening so the chest stretches. A subtle glow on the chest shows where the stretch is felt — in the chest, not the shoulder joint.",
    commonMistake: "stretching the shoulder joint instead of the chest",
    correct: "feel the stretch in the chest muscles only",
    cues: ["Forearm on the frame", "Lean gently forward", "Feel it in the chest"],
    tempo: "Hold, breathe",
    primaryFault: "shoulder strain",
    videoCandidate: false,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "worlds-greatest-stretch",
    name: "World's Greatest Stretch",
    category: "mobility",
    dose: "5 reps/side",
    image: "images/worlds-greatest-stretch.webp",
    printImage: "images/worlds-greatest-stretch.png",
    videoUrl: null,
    view: "side-ground-plane",
    frames: 2,
    muscles: "hips, hamstrings, upper back",
    sequence: "Frame 1: deep lunge position on the mat, both hands on the floor inside the front foot. Frame 2: same lunge, one arm rotated up toward the ceiling with the chest turned — the rotation comes from the upper back (curved arrow at the reaching arm). Rear knee can hover or rest.",
    commonMistake: "rotating from the lower back",
    correct: "rotate from the upper back, hips stay steady",
    cues: ["Deep lunge, hands inside foot", "Rotate from the upper back"],
    tempo: "Slow and controlled",
    primaryFault: "lumbar rotation",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "hip-flexor-stretch",
    name: "Hip Flexor Stretch",
    category: "mobility",
    dose: "30 sec/side",
    image: "images/hip-flexor-stretch.webp",
    printImage: "images/hip-flexor-stretch.png",
    videoUrl: null,
    view: "side-ground-plane",
    frames: 1,
    muscles: "hip flexors",
    sequence: "One figure in a half-kneeling position on the mat: rear knee down, front foot planted, torso tall, pelvis tucked slightly under so the stretch appears at the front of the rear hip (subtle glow there). A small arrow at the pelvis shows the gentle tuck.",
    commonMistake: "arching the low back instead of tucking the pelvis",
    correct: "tuck the pelvis slightly under; stay tall",
    cues: ["Rear knee down", "Tuck pelvis slightly under", "Stay tall"],
    tempo: "Hold, breathe",
    primaryFault: "low-back arch",
    videoCandidate: false,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "hamstring-stretch",
    name: "Hamstring Stretch",
    category: "mobility",
    dose: "30 sec/side",
    image: "images/hamstring-stretch.webp",
    printImage: "images/hamstring-stretch.png",
    videoUrl: null,
    view: "side",
    frames: 1,
    muscles: "hamstrings",
    sequence: "One standing figure with one heel placed forward on the floor, leg long, hinging forward from the hips with a LONG, straight spine (dashed line along the back). Subtle glow along the back of the extended leg. A small arrow at the hips shows the hinge.",
    commonMistake: "rounding the spine to reach further",
    correct: "long spine; hinge from the hips",
    cues: ["Long spine", "Hinge from the hips"],
    tempo: "Hold, breathe",
    primaryFault: "rounded spine",
    videoCandidate: false,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "calf-stretch",
    name: "Calf Stretch",
    category: "mobility",
    dose: "30 sec/side",
    image: "images/calf-stretch.webp",
    printImage: "images/calf-stretch.png",
    videoUrl: null,
    view: "side",
    frames: 1,
    muscles: "calves",
    sequence: "One standing figure leaning with both hands against a wall: one leg stepped back with the knee straight and the HEEL FLAT ON THE FLOOR (small emphasis mark at the heel), front knee bent. Subtle glow on the rear calf.",
    commonMistake: "letting the back heel lift off the floor",
    correct: "back heel stays down",
    cues: ["Hands on the wall", "Back leg long", "Back heel stays down"],
    tempo: "Hold, breathe",
    primaryFault: "heel lift",
    videoCandidate: false,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "shoulder-wall-slides",
    name: "Shoulder Wall Slides",
    category: "mobility",
    dose: "10 slow reps",
    image: "images/shoulder-wall-slides.webp",
    printImage: "images/shoulder-wall-slides.png",
    videoUrl: null,
    view: "side",
    frames: 2,
    muscles: "shoulders, upper back",
    sequence: "Frame 1: standing with the back against a wall, arms bent at 90 degrees with the backs of the hands and elbows touching the wall at shoulder height. Frame 2: arms slid up the wall overhead while the ribs stay down and the lower back does NOT arch away from the wall (dashed line along the wall contact). Arrows show the upward slide.",
    commonMistake: "arching the lower back as the arms rise",
    correct: "ribs down; lower back stays near the wall",
    cues: ["Back against the wall", "Slide arms slowly up", "Ribs down — no arch"],
    tempo: "Slow reps",
    primaryFault: "low-back arch",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "childs-pose",
    name: "Child's Pose",
    category: "mobility",
    dose: "45–60 sec",
    image: "images/childs-pose.webp",
    printImage: "images/childs-pose.png",
    videoUrl: null,
    view: "side-ground-plane",
    frames: 1,
    muscles: "lats, spine",
    sequence: "One figure kneeling on the mat, sitting back toward the heels, arms stretched long overhead on the floor, forehead resting toward the mat. Whole body relaxed — a calm resting stretch. Subtle glow along the sides of the back (lats).",
    commonMistake: "tensing up instead of relaxing",
    correct: "relax and breathe slowly into the stretch",
    cues: ["Sit back toward heels", "Arms long", "Breathe slowly"],
    tempo: "Hold, slow breathing",
    primaryFault: "tension",
    videoCandidate: false,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  },
  {
    id: "supported-deep-squat-hold",
    name: "Supported Deep Squat Hold",
    category: "mobility",
    dose: "20–30 sec",
    image: "images/supported-deep-squat-hold.webp",
    printImage: "images/supported-deep-squat-hold.png",
    videoUrl: null,
    view: "side-ground-plane",
    frames: 1,
    muscles: "hips, ankles",
    sequence: "One figure in a deep squat, holding onto a sturdy support (a door frame or table edge) in front with both hands, heels down (or working toward the floor — small emphasis mark at the heels). Relaxed, supported hold at the bottom of the squat.",
    commonMistake: "heels lifting off the floor",
    correct: "hold the support; heels down if possible",
    cues: ["Hold door or table", "Sit deep and relax", "Heels down if possible"],
    tempo: "Hold, breathe",
    primaryFault: "heel lift",
    videoCandidate: true,
    approved: true,
    approvedNote: "Approved by Ivan 2026-07-08 — Ivan-prompt batch (character-referenced)"
  }
];
